en = {
    hello: "Hello",
    restaurant: "Restaurant",
    menu: "Menu",
    order: "Order",
    orders: "Orders",
    place_order: "Place Order",
    my: "My",
    add: "Add",
    add_to_cart: "Add to Cart",
    cart: "Cart",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    sign_out: "Sign Out",
    create_account: "Create Account",
    email: "Email",
    phone: "Phone",
    username: "Username",
    password: "Password",
    price: "Price",
    total: "Total",
    total_price: "Total Price",
    quantity: "Quantity",
    name: "Name",
    address: "Address"
}