es = {
    hello: "Hola",
    restaurant: "Restaurante",
    menu: "Menú",
    order: "Pedido",
    orders: "Pedidos",
    place_order: "Hacer Pedido",
    my: "Mi",
    add: "Añadir",
    add_to_cart: "Añadir al Carrito",
    cart: "Carrito",
    sign_in: "Intentificarte",
    sign_up: "Registrarse",
    sign_out: "Salir",
    create_account: "Crea Cuenta",
    email: "Email",
    phone: "Teléfono",
    username: "Nombre de teléfono",
    password: "Contraseña",
    price: "Precio",
    total: "Total",
    total_price: "Total Precio",
    quantity: "Cantidad",
    name: "Nombre",
    address: "Dirección"
}