es = {
    lang: "es",
    hello: "Hola",
    restaurant: "Restaurante",
    menu: "Menú",
    order: "Pedido",
    orders: "Pedidos",
    place_order: "Realizar Pedido",
    my: "Mi",
    add: "Añadir",
    add_to_cart: "Añadir al Carrito",
    cart: "Carrito",
    sign_in: "Intentificarte",
    sign_up: "Registrarse",
    sign_out: "Cerrar Sesión",
    create_account: "Crea Cuenta",
    email: "Email",
    phone: "Teléfono",
    username: "Nombre de Usuario",
    password: "Contraseña",
    price: "Precio",
    total: "Total",
    total_price: "Total Precio",
    quantity: "Cantidad",
    name: "Nombre",
    address: "Dirección",
    status: "Estado",
    remove: "Retirar",
    currency_symbol: "€",
    currency_rate: 0.84,
    currency: "EUR",
    comment: "Comentario",
    guest: "Invitado",
    home: "Página de Inicio",
    view_orders: "Ver Pedidos"
}