fr = {
    hello: "Bonjour",
    restaurant: "Restaurant",
    menu: "Menu",
    order: "Commande",
    orders: "Commandes",
    place_order: "Commande",
    my: "Ma",
    add: "Ajoute",
    add_to_cart: "Ajoute au Panier",
    cart: "Panier",
    sign_in: "Se Logger",
    sign_up: "S'Enregitrer",
    sign_out: "Se Déconnecter",
    create_account: "Créez un Compte",
    email: "Email",
    phone: "Téléphone",
    username: "Nom d'Utilisateur",
    password: "Mot de Passe",
    price: "Prix",
    total: "Total",
    total_price: "Prix Total",
    quantity: "Quantité",
    name: "Nom",
    address: "Adresse"
}