pt = {
    hello: "Olá",
    restaurant: "Restaurante",
    menu: "Cardápio",
    order: "Pedido",
    orders: "Pedidos",
    place_order: "Fazer Pedido",
    my: "Meu",
    add: "Adicionar",
    add_to_cart: "Adicionar ae Carrinho",
    cart: "Carrinho",
    sign_in: "Entrar",
    sign_up: "Increver-se",
    sign_out: "Assinar",
    create_account: "Criar Conta",
    email: "Email",
    phone: "Telefone",
    username: "Nome de Usuário",
    password: "Senha",
    price: "Preço",
    total: "Total",
    total_price: "Preço Total",
    quantity: "Quantidade",
    name: "Nome",
    address: "Morada"
}